### ISSUE TITLE
数据清洗能否继续优化一下

### ISSUE THREAD

**Issue by panghaibin** [sunbqxyz/china_covid_riskareas_history#1]
看了一下清洗数据的结果，似乎有些不太理想，例如 2022-03-01 中，四川成都的结果，将小区里的XX栋单独分开了

![image](https://user-images.githubusercontent.com/63835145/190097537-218ed391-15ec-42d1-bc2a-e2959e84ab53.png)

另外原始数据似乎不太完整，例如上述 2022-03-01 的就找不到，以及浙江省卫健委应该是江苏的吧， `Zhejiang` 文件夹下的标题全是江苏的

如果方便希望可以将完整的原始数据上传，对于数据清洗的代码，可以再优化一下，或者将其开源出来，看看有没有优化的空间

**Comment by sunbqxyz** [comment]
感谢关注这一数据集，数据清洗方面我会进一步关注，源码本周我会整理一下然后放出。
关于您指出的两个问题：
1.四川成都的原始数据中，混用了顿号、逗号、分号作为分割标志，可能导致程序的分割处理出现了问题，我将进行调试，这里附上原始文本。
`四川省成都市（14个）：高新区中和街道长城馨苑小区，中和街道乐活公社小区，石羊街道天府世家小区、桂溪街道世龙公馆，中和街道中德世邦和庭（原中德K区）1栋、7栋、8栋，中和街道名著司南小区7栋、8栋、9栋、10栋，桂溪街道英郡三期小区；温江区公平街道佳兆业·丽晶公馆小区；金牛区驷马桥街道沙河云景湾小区；金堂县赵镇街道生态水城澜岸小区；天府新区华阳街道龙河社区凯华丽景小区、伏龙社区丽景苑小区、四河社区四河小区、华阳街道洛森堡新殿蝶郡小区。`
2.原始数据问题，文件夹被错误命名了，同时有部分数据尚未上传，对于这一错误我已进行修正。需要注意的是，在这一修正过后，`zhejiang`文件夹下的文件名中的日期可能对应2020/2021/2022年，对于这一问题，我建议如您希望使用相关数据，可以先按照文件名将其分割为标题以日期开头和以“截止”开头的两类，其中“截止”开头的对应较靠后的日期，个人猜测这一文件命名的变化是由于卫健委负责人员变动所导致的。

**Comment by sunbqxyz** [comment]
由于原始代码较为散乱，同时考虑到原始数据自身存在的问题（正如前面提到的，原始数据的状况并不理想，很多数据分割符号适使用不规范，同时存在大量对上级行政区域的省略），我直接使用之前发布的数据进行了清洗。目前，所有区域的县级地址已通过高德地图API结合手工录入的方式补全；同时也核查了缺少最低级行政区划信息的地址信息，基本能够确信目前缺失第四级地址信息即表明风险区域为全境。
如果在使用中发现数据有进一步的问题，烦请继续反馈，万分感谢
